name: my_website
description: <Jhon/>.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_theme_switcher: ^2.0.6
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  responsive_framework: ^0.1.7
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/images/social/
    - assets/images/companies/
    - assets/images/technology/
